version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '4050:80'
    networks: 
      - nettdg
  mongo:
    image: mongo
    environment: 
      - "MONGO_INITDB_DATABASE=db_tdg"
      - "MONGO_INITDB_ROOT_USERNAME=user_tdg"
      - "MONGO_INITDB_ROOT_PASSWORD=tdg_123!-"
      - "MONGO_DATA_DIR=/data/db"
      - "MONGO_LOG_DIR=/dev/null"
    ports: 
      - 27018:27017
    volumes: 
      - "voltdgdb:/data/db"
      - "volconfgdb:/data/configdb"
    networks: 
      - nettdg
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    environment: 
      - "MONGO_INITDB_DATABASE=db_tdg"
      - "MONGO_INITDB_ROOT_USERNAME=user_tdg"
      - "MONGO_INITDB_ROOT_PASSWORD=tdg_123!-"
      - "MONGO_HOST=mongo"
      - "MONGO_PORT=27017"
    networks: 
      - nettdg
    volumes: 
      - /app/node_modules
      - ./server:/app
  client:
    build: 
      dockerfile: Dockerfile
      context: ./client
    volumes: 
      - /client/node_modules
      - ./client:/client
    networks: 
      - nettdg
    ports: 
      - "4200:4200"
volumes: 
  voltdgdb:
  volconfgdb:
networks: 
  nettdg: